### PR TITLE
Travis cache environment

### LINKED ISSUE #15: Add Caching to Travis CI
Currently Travis CI downloads Miniconda and builds the conda env from scratch every time.  It would be better to:

- Cache conda install script and miniconda install directory
- Every time diff existing and new conda install shell scripts and completely rebuild if different
- if only difference is in environment.yml call `conda env update --prune`
- otherwise leave conda as is

This should save about 2 minutes per Travis run.

### PR DESCRIPTION
**Pull request by ferria**
Fixes #15.

Caching has been added to Travis CI:

1. If update to Miniconda then everything rebuilt
2. If environment.yml updated then conda env updated
2. Otherwise all left alone

This reduces Travis build time by ~1 minute from 2m30s to 1m30s when nothing needs to be rebuilt and around 2m + storing cache when there is a small env change (case 1 should occur the vast majority of the time).

### CODE REVIEW

**Comment by ferria** [comment]
Since there are a lot of commits here for what is essentially one feature, I am thinking that it may be a good idea to squash and merge when we merge this.  Thoughts? @Behemyth @zyteka

**Comment by zyteka** [comment]
Looks good

**Comment by zyteka** [comment]
Looks good

**Comment by zyteka** [comment]
Looks good

**Pull request merged**
